puppetlabs/jvm-ssl-utils

src/clojure/puppetlabs/certificate_authority/core.clj, test/puppetlabs/certificate_authority/core_test.clj
This PR adds a simple wrapper around .getSubjectX500Principal and the existing get-cn-from-x500-principal functions.
=> Add cn-from-x509-certificate function

test/puppetlabs/certificate_authority/core_test.clj
This PR specifies a key size of 512 to the generate-key-pair function in the cn-from-x509-certificate test, to speed it up
=> Add key size parameter to cn-from-x509-certificate test

CHANGELOG.md, project.clj
Updated changelog to reflect changes from https://github.com/puppetlabs/jvm-certificate-authority/pull/43
=> (MAINT) Updated changelog for 0.6.1, bumped version to 0.6.2-SNAPSHOT

src/clojure/puppetlabs/ssl_utils/core.clj, test/puppetlabs/ssl_utils/core_test.clj
Add generate-ssl-context function, which, when given a map of
options, either configures an SSLContext, returns nil if no
SSL options were provided, or throws an exception if an incomplete
SSL configuration was provided.
=> (TK-146) Add generate-ssl-context function

src/clojure/puppetlabs/ssl_utils/simple.clj, test/puppetlabs/ssl_utils/simple_test.clj
This includes the changes discussed in #55 as well as an implementation of the options map parameter.
No JIRA necessary.
=> (MAINT) Simple API followup

src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, test/puppetlabs/ssl_utils/extensions_utils_test.clj
This PR does two things. 
1. There was a bug when attempting to decode some a `General Name` values, specifically in the case where an IP address or an OID. Previously an exception was being thrown. Now they are properly decoded.
2. Now unknown values are returned as Base64-encoded strings, preceded by `base64:` instead of byte arrays. Base64-encoded data is much easier to print to the screen and examine.
=> (Server-816) Display unknown extensions as Base64

src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
Previously, if `getCommonNameFromX500Name` were called with an x500Name
that had no CN attribute within it, an `ArrayIndexOutOfBoundsException`
would be thrown.  With changes in this commit, the method would instead
return an empty string for this case.
=> (MAINT) Handle getCommonName for X500Name with no CN

src/clojure/puppetlabs/ssl_utils/core.clj, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
This commit adds new helpers --
get-subject-from-x509-certificate in Clojure /
SSLUtils.getSubjectFromX509Certificate() in Java -- for extracting the
full subject from an X509Certificate object.  The helpers return the
subject in BCStyle since each of the related helpers already in
jvm-ssl-utils also use BCStyle.
This commit also changes each of the related helpers which implicitly
use BCStyle, by virtue of it being the default style, to explicitly use
BCStyle.  This is done to protect against the possibility of a future
default style change in BouncyCastle causing some of the helpers to
mangle string values if differing styles are used among helpers to
encode vs. decode values.
=> (SERVER-1545) Add helpers for getting subject from a certificate

CHANGELOG.md
This commit adds a note to the `CHANGELOG.md` file for the 0.8.2
release.
=> (MAINT) Prep for 0.8.2 release

project.clj
The version of bouncycastle we are shipping is over 2 years old.
We've had a user report incompatibilities between it and recent
certificates generated by external tools.
This commit updates us to the most recent version, which contains
many bug fixes and features compared to the older version we were
shipping, but should be backward-compatible.
=> (PE-18417) Update to bouncycastle 1.55

src/clojure/puppetlabs/ssl_utils/core.clj
The addition of schemas in this library made the arguments acceptable
to `generate-ssl-context` too restrictive for the way the library was
typcially used. This commit relaxes the requirements of the
`SSLContextOptions` schema to improve backwards compatability.
=> (maint) Relax schema constraints on generate-ssl-context

.travis.yml, project.clj, src/clojure/puppetlabs/ssl_utils/core.clj, src/clojure/puppetlabs/ssl_utils/simple.clj, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
The work that instigated the PR is in 545d071, the majority of the code changes and the reasons for them are within that commit message (pasted below).
It also updates our version of bouncycastle and clj-parent. This does not pull in the Java 9 compatibility changes in clj-parent, though it upgrades past the point where compatibility of Java 7 was assured. It also fixes existing deprecation warnings. Happy to pull those out into a separate PR, but figured it was good to update while I was here.
```
This commit adds a general `objs->pem!` similar to the more specific
{crl,cert}->pem! functions so we may efficiently serialize chain/bundles
of PKI objects.
It also adds a pem->ca-crl to provide an analog to pem->ca-cert though
its usage in puppetserver does not allow us to require the ca cert …
```
=> (SERVER-2205) Changes to support multiple CRLs; (maint) target 1.0.0

src/clojure/puppetlabs/ssl_utils/core.clj, test/puppetlabs/ssl_utils/core_test.clj
Simon (reporter in https://tickets.puppetlabs.com/browse/SERVER-2440) correctly points out that `bytes[]` is parsed as two separate tokens, `bytes` (which is a function in `clojure.core`) and `[]`, an empty vector.
Since schema adds primitives we can use the shorthands `bytes` and `chars` in the schemas.
Also added basic tests that ensures that byte and char arrays both satisfy `Readerable` and `Writerable`.
=> (SERVER-2440) fix primitive type name in Reader-/Writerable schemas

.travis.yml, project.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
Move the bouncycastle jar to the dev profile. This will allow us
to specify the bouncycastle jars on the classpath at runtime like
we do for logging configuration. At installation time, we can install
the FIPS-compliant version of the jars, or the standard versions.
The FIPS version of the jar has a reduced number of classes compared to
the standard provider, but all the base functionality is there. Reworked
SSLUtils and ExtensionsUtils to use the classes that are provided in
both versions, and determine which provider based on availability on the
classpath.
Added additional build stages to Travis CI so that we test FIPS and
non-FIPS on both JDK 8 and JDK 11.
=> (PDB-4357) FIPS support

jdk11-fips-security, jdk8-fips-security, project.clj, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
For full FIPS certification, you must disable the security providers
that are not compliant and make the BC FIPS provider the primary
provider.
The BC FIPS provider requires the BCFKS keystore implementation instead
of JKS.
The Sun SSL provider isn't present, but adding the BC-TLS jar gives us a
proper TLS implementation.
=> (PE-26658) apply JVM security policy to FIPS

src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java
The type checking when getting extensions out of a CSR is more
restrictive than in bouncy caste's own functions. This commit updates us
to use their `getInstance` method for extensions, which is less brittle.
Our type checking breaks when updating to BC 1.63, which switched from
using DER types to using DL types when parsing pretty much everywhere.
=> (SERVER-2801) Use extension processing method directly

project.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java
This commit updates the exception we catch when parsing an unwrapped
Netscape comment cert extension from a legacy Puppet cert. Newer
versions of Bouncy Castle added an extra error case when attempting to
parse extension byte arrays, that our legacy certs hit, because the
extension values are not byte arrays but unwrapped strings. Previously,
we would hit an EOFException, but now it throws a generic IOException
before proceeding to the check we used to fail. IOException is a
superclass of EOFException, so by catching the former, we are also
backwards compatible.
=> (SERVER-2801) Catch IOException for malformed Netscape comment ext

src/clojure/puppetlabs/ssl_utils/core.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, test/puppetlabs/ssl_utils/core_test.clj
This commit adds functions to determine whether a given CRL is a delta CRL or
not. We do not support delta CRLs (which contain only changes since the base CRL
was published, rather than the whole list of revoked certs), so this will allow
us to error cleanly if we encounter a delta CRL, particularly when consuming CRL
updates from an external CA.
=> (SERVER-2550) Add functions to identify delta CRLs

src/clojure/puppetlabs/ssl_utils/core.clj, test/puppetlabs/ssl_utils/core_test.clj, test/puppetlabs/ssl_utils/testutils.clj
This PR adds a function to get the value of the CRL Number extension from a
given CRL. This value is used to determine how new the CRL is (compared to other
CRLs issued by the same cert).
Also fixes a couple `illegal reflective access` warning.
=> (SERVER-2550) Add `get-crl-number` function

test/puppetlabs/ssl_utils/testutils.clj
This commit adds a test utility for generating multiple CRLs for a given issuer.
This can be used with `generate-cert-chain-with-crls` to generate a cert chain
where each cert has issued multiple CRLs. This will facilitate testing CRL
updates, ensuring that the appropriate CRL is used in various situations.
=> (SERVER-2550) Add testutil for generating multiple CRLs

src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java
Versions of bouncy castle past 1.63 introduced additional `equals`
methods to the `ASN1ObjectIdentifier` class, with more specific type
signatures. However, these methods to not exist in FIPS BC. This commit
adds some casts to `Object` to places where we call this method, to
ensure we always get the more general API that exists in both versions.
Note that this caused an issue when ssl-utils class files compiled with
newer non-FIPS BC were used when running with FIPS inside Puppetserver.
The compiled files expected the new APIs, which were not available when
the FIPS jar was used at runtime.
=> (maint) Ensure compatibility with bc-fips API

project.clj
java.version on some platforms differs from what Puppetserver's project file tries to parse.
java.specification.version is however guaranteed to match the expected format.
See https://github.com/puppetlabs/puppetserver/pull/2539 for the same fix.
=> Use java.specification.version for version check

src/clojure/puppetlabs/ssl_utils/core.clj, test/puppetlabs/ssl_utils/core_test.clj, test/puppetlabs/ssl_utils/testutils.clj
Previously, we only allowed generating CA cert extensions with serial
and issuer values for the authority key identifier. This is not valid
with some libraries (notably Ruby's openssl), which requires the auth
key id to include the key ID from the issuer's public key. This adds an
arity to the function that generates CA extensions, to allow generating
the more correct form.
=> (maint) Allow CA extensions to include auth key id from issuer public key

jdk11-fips-security, jdk8-fips-security
There is an issue with the latest bc-fips version involving circular
provider loading, that can be fixed by using the full class name for the
BCJSSE FIPS provider, rather than relying on an alias. This commit
updates our java-security file for Java 11 to use the full name.
It also updates the key manager factory algorithm following a
recommendation from the BC maintainers.
=> (PE-32070) Update Java 11 security file for new BCFIPS

jdk11-fips-security, jdk8-fips-security
The PKIX factory is correct for non-FIPS BC, but in FIPS mode we want to
use BCFKS.
=> (PE-32070) Use BCFKS key factory in FIPS mode

project.clj
This update brings in Bouncy Castle 1.70, which has improved TLS 1.3
support.
=> (SERVER-3135) Update clj-parent to 4.9.2

src/clojure/puppetlabs/ssl_utils/core.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj, test/puppetlabs/ssl_utils/testutils.clj
Previous to this change, the Authority Key would be recomputed based
on the public key of the certificate of the ca; this change enables
copying from an existing certificate, allowing for different key
types to be used, specifically whatever key type the CA cert has.
=> (SERVER-2662) Don't recompute Authority Key extensions

project.clj
This updates clj-parent to 5.2.6 which contains references to the newer versions of bouncy-castle. In a recent change bouncycastle renamed their library to 18on from 15on. The references in this project were also updated.
=> (maint) update clj-parent to 5.2.6

CHANGELOG.md, project.clj, src/clojure/puppetlabs/ssl_utils/core.clj, src/clojure/puppetlabs/ssl_utils/simple.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj, test/puppetlabs/ssl_utils/simple_test.clj
This adds support in the "simple" namespace for adding attributes to CSRs. It adds a test to demonstrate the behavior.
It also fixes several problems, including a typo in the "get-keys" function which was associating a name with the wrong key, as well as removing use of a deprecated conversion routine.
Some require organization was done as well.
=> (PE-36454) add support for adding attributes to csrs, fix issues

.clj-kondo/config.edn, .github/workflows/clojure-linting.yaml, .github/workflows/pr-testing.yaml, jdk17-fips-security, project.clj, src/clojure/puppetlabs/ssl_utils/core.clj, test/puppetlabs/ssl_utils/core_test.clj, test/puppetlabs/ssl_utils/extensions_utils_test.clj, test/puppetlabs/ssl_utils/testutils.clj
This adds kondo and eastwood linting tests. It resolves some of
the issues identified by the linters.
It also enables lein based testing for jdk8, 11 and 17.
=> (maint) add clojure linting and PR testing github actions

CHANGELOG.md, src/clojure/puppetlabs/ssl_utils/core.clj, src/java/com/puppetlabs/ssl_utils/ExtensionsUtils.java, src/java/com/puppetlabs/ssl_utils/SSLUtils.java, test/puppetlabs/ssl_utils/core_test.clj
This adds a function to retrieve the attributes from Certificate Signing Requests. It adds tests to demonstrate the behaviors.
=> (PE-36455) add support for reading attributes from certificate signing requests

CHANGELOG.md, README.md, project.clj, src/java/com/puppetlabs/ssl_utils/SSLUtils.java
This adds a backdoor to allow the CRL 5 year expiration to be overridden with a value in seconds.
=> (maint) add ability to override CRL lifetime
